#!/usr/bin/env python3
"""Reader comparison: the V4 answer prompts of the step 3 cohorts sent to Vertex-hosted models.

P5's upper-reference measurement (docs/DESIGN-REPAIR-PLAN.md), requested by the user on October 10,
2026: does a hosted model answer Boros's assembled V4 prompts better, and more repeatably, than the
selected local Qwen? Record: docs/READER-COMPARISON.md.

Readers: ``claude-sonnet-5-5`` and ``claude-haiku-5-5`` (vertex_anthropic.py) and ``gemini-3.8-flash``
(vertex_gemini.py), Vertex AI project llm-train-482420, location global. The Qwen baseline is the
V4 arm of the two earlier local runs on the same inputs (the step 3 replay and the V5 test).

Inputs are the exact answer request bodies the ordinary path assembles for the 94 V4 runs of the
step 3 replay (retrieval-on-21, preference-27, temporal-25, recent-only-21). ``capture`` rebuilds
them offline with the retrieval harness's delivery binary (Tests/Evaluation/DeliveryHarness.swift)
and its loopback tokenizer stand-in: the coordinator stops at the answering boundary and the
harness writes the prepared answer work's request body, which the runner would dispatch unchanged.
No local or remote answer is generated by ``capture``. Each capture is checked against the step 3
declaration: the same runner input, the same delivered ranges and the V4 framing.

Only the messages of a captured body are sent: the System message as the system instruction and the
remaining turns in order. Qwen sampling fields (temperature, seed, top_k and so on) are not sent;
no hosted model here accepts a pinned temperature through these adapters, so sampling is the
provider default and repeatability is measured with replicates.

Commands: ``capture``, ``count`` (free token counts), ``declare``, ``run``, ``measure``,
``judge-set`` and ``score``. Paid commands are ``run`` only; judging uses judge_calibration_run.py.

Privacy: request bodies, answers and raw responses stay in the private output directory (0700
directories, 0600 files) and are never printed. stdout carries counts, hashes, identifiers and
fixed codes only. The Boros application is unchanged and still processes text only locally.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from decimal import Decimal
import json
import os
from pathlib import Path
import statistics
import sys
import tempfile
import threading
import time

sys.path.insert(0, str(Path(__file__).resolve().parent))
import answer_presentation_replay as replay  # noqa: E402
import framing_v4_variants_replay as v4v  # noqa: E402
import framing_v5_replay as v5plan  # noqa: E402
import vertex_anthropic as va  # noqa: E402
import vertex_gemini as vg  # noqa: E402

ROOT = replay.ROOT
VERSION = "reader-comparison-v1"
V4 = replay.V4
REPLICATES = 3
COHORT_ORDER = v4v.COHORT_ORDER
EXCLUDED_FROM_COUNTS = v4v.EXCLUDED_FROM_DECISION
QWEN = replay.MODEL
# Readers, in dispatch order within a question. Prices are USD per million tokens, declared per run
# (sources in the declaration). Gemini's maxOutputTokens adds a thinking allowance to the Qwen output
# cap, because its thought tokens count against that limit and cannot be turned off.
READERS = {
    "claude-sonnet-5-5": {"route": "anthropic", "thinking": {"type": "between_tools"}, "input_usd": "2.00",
                          "output_usd": "10.00", "price_source": "Vertex AI pricing as declared for the default judge "
                          "(Sonnet 5.5 input $2.00, output $10.00); verified 2026-10-09"},
    "claude-haiku-5-5": {"route": "anthropic", "thinking": {"type": "disabled"}, "input_usd": "0.10",
                         "output_usd": "0.50", "price_source": "Anthropic model reference (Haiku 5.5 $0.10 / $0.50 "
                         "for prompts of 100K tokens or fewer); every prompt here is far below 100K"},
    "gemini-3.8-flash": {"route": "gemini", "thinking_level": "low", "thinking_allowance": 2048, "input_usd": "1.50",
                         "output_usd": "7.50", "price_source": "list rate reported by third-party pricing pages "
                         "($1.50 / $7.50; a promotional $0.75 / $3.75 is also reported); the list rate is declared "
                         "so the cap is conservative; thought tokens are billed as output"},
}
SPENDING_CAP_USD = Decimal("30")
WORKERS = 6
RETRYABLE = ("http_status_429", "http_status_500", "http_status_502", "http_status_503", "http_status_504",
             "transport_failed")
RETRY_DELAYS = (10, 30)
AUTHORIZATION = ("user, 2026-10-10, in chat: 'using the llm-train-482420 gcp project, can you try out the following "
                 "models and see how they do for what we need? gemini-3.8-flash, haiku 5.5, sonnet 5.5' after the "
                 "repeatability problem of the local model; the coordinator declared the cohorts, three replicates, "
                 "settings and a $30 generation cap (judging capped separately at $10)")


class ComparisonError(Exception):
    pass


def require(condition, code):
    if not condition:
        raise ComparisonError(code)


def now():
    return datetime.now(timezone.utc).isoformat()


def case_name(cohort, qid):
    return f"{cohort}--{qid}"


def answer_name(model, cohort, qid, replicate):
    return f"{model}/{case_name(cohort, qid)}--r{replicate}"


# --------------------------------------------------------------------------- reference run

def reference_runs(reference: Path):
    """(cohort, question ID) -> (step 3 run index, declared entry) for the V4 arm."""
    declaration = json.loads((reference / "declaration.json").read_text())
    require(declaration.get("version") == v4v.VERSION, "reference_declaration_version")
    out = {}
    for index, entry in enumerate(declaration["runs"]):
        if entry["arm"] == "v4-default":
            out[(entry["cohort"], entry["question_id"])] = (index, entry)
    require(len(out) == 94, "reference_v4_runs_not_94")
    return declaration, out


def native_answer(output: Path, rows, index, ordinal):
    """(report, attempt item, answer text) of a finished local run, or Nones."""
    finished = [row for row in rows if row["run"] == index and row.get("invocation_started") is True]
    native = output / (finished[-1]["directory"] if finished else "missing")
    if not (native / "report.json").exists():
        return None, None, None
    report = json.loads((native / "report.json").read_text())
    item = [attempt for attempt in report["attempts"] if attempt["ordinal"] == ordinal][0]
    path = native / item["answer_file"]
    return report, item, (path.read_text() if path.exists() else None)


# --------------------------------------------------------------------------- capture

def capture(args):
    """Offline: the exact V4 answer request body for each of the 94 step 3 V4 runs. No generation."""
    import retrieval_harness as harness
    output = args.output.absolute()
    require(output.is_relative_to(ROOT / ".build"), "output_outside_build")
    reference = args.reference.absolute()
    ref_declaration, ref_runs = reference_runs(reference)
    ref_ledger = replay.ledger(reference)
    plan = v4v.cohorts()
    frozen = v4v.frozen_inputs(args.dataset, plan)
    replay.private_directory(output)
    requests = output / "requests"
    replay.private_directory(requests)
    cache_root = output / "harness"
    replay.private_directory(cache_root)
    binary, implementation = harness.compile_harness(cache_root)
    endpoint = harness.OfflineEndpoint(args.tokenizer, 0).start()
    rows = []
    try:
        with tempfile.TemporaryDirectory(prefix="boros-reader-capture-", dir=output) as scratch_name:
            scratch = Path(scratch_name)
            os.chmod(scratch, 0o700)
            for cohort in COHORT_ORDER:
                cases, _arm = plan[cohort]
                for qid, run, strategy, _policy in cases:
                    index, entry = ref_runs[(cohort, qid)]
                    history, document, _ = frozen[(qid, run)]
                    require(v5plan.e_digest(document) == entry["runner_input_sha256"], "runner_input_mismatch")
                    arm = v4v.gold_arm(cohort, strategy)
                    require(arm == entry["declared_gold_arm"], "arm_mismatch")
                    directory = requests / case_name(cohort, qid)
                    require(not directory.exists(), "capture_exists")
                    replay.private_directory(directory)
                    hybrid = [attempt for attempt in document["attempts"] if attempt["strategy"] == "hybrid"][0]
                    configuration = dict(document["configuration"], endpoint=endpoint.url)
                    base = {"version": 1, "cache_directory": str(cache_root / "stores" / v5plan.e_digest(document)),
                            "events": document["events"], "configuration": configuration,
                            "question": {key: hybrid[key] for key in ("project_id", "conversation_key", "prompt",
                                                                      "question_time")},
                            "arms": [arm], "declared_source_ids": None, "capture_directory": str(directory)}
                    selection = harness.run_process(binary, "select", base, scratch, "capture")
                    item = (selection.get("attempts") or [{}])[0]
                    sizes = {event["id"]: len(event["text"].encode()) for event in document["events"]}
                    ranges = v5plan.delivered_ranges(item.get("recent_source_ids") or [], item.get("evidence") or [], sizes)
                    body_path = directory / (arm + ".request.json")
                    row = {"cohort": cohort, "question_id": qid, "arm": arm, "reference_run": index,
                           "runner_input_sha256": entry["runner_input_sha256"],
                           "process_failure": selection.get("process_failure"), "failure": item.get("failure"),
                           "preparation_completed": bool(item.get("preparation_completed")),
                           "runner_started": bool(item.get("runner_started")),
                           "context_framing": item.get("context_framing"),
                           "delivered_ranges_sha256": replay.ranges_digest(ranges),
                           "delivery_matches_reference": replay.ranges_digest(ranges)
                           == entry["declared_delivered_ranges_sha256"],
                           "harness_prompt_tokens": item.get("prompt_tokens"),
                           "request_sha256": item.get("request_sha256"), "request_bytes": item.get("request_bytes"),
                           "maximum_output": entry["maximum_output"], "question_type": entry["question_type"],
                           "abstention": entry["abstention"], "declared_gold_delivery": entry["declared_gold_delivery"],
                           "citation_labels": item.get("citation_labels")}
                    report, ref_item, _ = native_answer(reference, ref_ledger, index, entry["attempt"])
                    row["reference_prompt_tokens"] = ((ref_item or {}).get("provider_usage") or {}).get("promptTokens")
                    row["reference_label_map_equal"] = _labels(ref_item and ref_item.get("citation_labels")) \
                        == _labels(item.get("citation_labels"))
                    if body_path.exists():
                        raw = body_path.read_bytes()
                        row["body_digest_matches"] = replay.digest(raw) == item.get("request_sha256")
                        messages = request_messages(raw)
                        row["message_roles"] = [message["role"] for message in messages]
                        row["system_sha256"] = replay.digest(messages[0]["content"].encode()) \
                            if messages[0]["role"] == "system" else None
                    rows.append(row)
                    print(json.dumps({key: row.get(key) for key in ("cohort", "question_id", "failure",
                                      "delivery_matches_reference", "body_digest_matches", "harness_prompt_tokens",
                                      "reference_prompt_tokens")}), flush=True)
    finally:
        endpoint.stop()
    require(not any(row["runner_started"] for row in rows), "answer_runner_started")
    manifest = {"version": VERSION, "kind": "reader-comparison-captures", "recorded_at_utc": now(),
                "reference": {"path_name": reference.name, "declaration_sha256":
                              replay.digest((reference / "declaration.json").read_bytes()),
                              "binary_sha256": ref_declaration["binary"]["sha256"]},
                "harness": implementation, "endpoint_counters": endpoint.counters, "rows": rows,
                "summary": capture_summary(rows)}
    replay.private_write(output / "captures.json", replay.canonical(manifest) + b"\n")
    print(json.dumps({"captures": len(rows), **manifest["summary"],
                      "captures_sha256": replay.digest((output / "captures.json").read_bytes())}))


def _labels(value):
    return sorted((entry.get("label"), entry.get("event_id"), entry.get("kind")) for entry in value or [])


def capture_summary(rows):
    differences = [row["harness_prompt_tokens"] - row["reference_prompt_tokens"] for row in rows
                   if isinstance(row.get("harness_prompt_tokens"), int) and isinstance(row.get("reference_prompt_tokens"), int)]
    return {"complete": sum(1 for row in rows if row.get("body_digest_matches") and row["preparation_completed"]),
            "delivery_matches_reference": sum(1 for row in rows if row["delivery_matches_reference"]),
            "framing_v4": sum(1 for row in rows if row.get("context_framing") == V4),
            "label_map_equal": sum(1 for row in rows if row["reference_label_map_equal"]),
            "prompt_token_difference_min": min(differences) if differences else None,
            "prompt_token_difference_max": max(differences) if differences else None,
            "distinct_system_messages": len({row.get("system_sha256") for row in rows})}


def request_messages(raw: bytes):
    """The role messages of a captured OpenAI-style body, validated."""
    body = json.loads(raw)
    require(isinstance(body, dict) and isinstance(body.get("messages"), list) and body["messages"], "body_invalid")
    for message in body["messages"]:
        require(isinstance(message, dict) and set(message) == {"role", "content"}
                and message["role"] in ("system", "user", "assistant") and isinstance(message["content"], str),
                "body_messages_invalid")
    return body["messages"]


def load_captures(output: Path):
    manifest = json.loads((output / "captures.json").read_text())
    require(manifest.get("version") == VERSION, "captures_version")
    require(manifest["summary"]["complete"] == len(manifest["rows"]) == 94, "captures_incomplete")
    require(manifest["summary"]["delivery_matches_reference"] == 94 and manifest["summary"]["framing_v4"] == 94,
            "captures_do_not_match_reference")
    return manifest


def captured_body(output: Path, row):
    raw = (output / "requests" / case_name(row["cohort"], row["question_id"]) / (row["arm"] + ".request.json")).read_bytes()
    require(replay.digest(raw) == row["request_sha256"], "captured_body_changed")
    return request_messages(raw)


# --------------------------------------------------------------------------- provider calls

def max_output(model, row):
    reader = READERS[model]
    return row["maximum_output"] + (reader.get("thinking_allowance") or 0)


def generation_request(model, messages, row):
    reader = READERS[model]
    if reader["route"] == "anthropic":
        return va.generation_url(model=model), va.payload(messages, max_output(model, row), model=model,
                                                           thinking=reader["thinking"])
    return vg.generation_url(model), vg.payload(messages, max_output(model, row), thinking_level=reader["thinking_level"])


def count_request(model, messages):
    if READERS[model]["route"] == "anthropic":
        return va.count_url(), va.count_payload(messages, model=model)
    return vg.count_url(model), vg.count_payload(messages)


def send(model, url, body, token):
    return (va.post if READERS[model]["route"] == "anthropic" else vg.post)(url, body, token)


def parse(model, raw):
    """(text, usage, stop reason, failure). A response cut at the output limit keeps its text and is
    recorded as incomplete, as a local answer at its cap would be."""
    route = READERS[model]["route"]
    module = va if route == "anthropic" else vg
    metadata = module.response_metadata(raw)
    try:
        text, usage = module.parse_response(raw, model) if route == "gemini" else module.parse_response(raw, model=model)
        return text, usage, metadata["stop_reason"], None
    except va.VertexError as error:
        code = str(error)
        if code != "response_incomplete":
            return None, None, metadata["stop_reason"], code
    value = json.loads(raw)
    if route == "anthropic":
        text = "".join(block.get("text", "") for block in value.get("content") or [] if block.get("type") == "text")
        usage = va.parse_usage(value)
    else:
        parts = ((value.get("candidates") or [{}])[0].get("content") or {}).get("parts") or []
        text = "".join(part.get("text", "") for part in parts if part.get("thought") is not True)
        usage = vg.parse_usage(value)
    return text, usage, metadata["stop_reason"], "incomplete_result"


def pricing(model):
    return va.Pricing(READERS[model]["input_usd"], READERS[model]["output_usd"])


# --------------------------------------------------------------------------- count

def count(args):
    """Free token counts of every captured input on every reader's count endpoint."""
    output = args.output.absolute()
    manifest = load_captures(output)
    token = va.AccessTokens()
    rows = []
    for row in manifest["rows"]:
        messages = captured_body(output, row)
        for model in READERS:
            url, body = count_request(model, messages)
            raw = send(model, url, body, token())
            tokens = va.parse_count(raw) if READERS[model]["route"] == "anthropic" else vg.parse_count(raw)
            rows.append({"cohort": row["cohort"], "question_id": row["question_id"], "model": model,
                         "input_tokens": tokens, "max_output_tokens": max_output(model, row)})
    totals = {}
    for model in READERS:
        mine = [row for row in rows if row["model"] == model]
        price = pricing(model)
        worst = sum(price.microusd(row["input_tokens"], row["max_output_tokens"]) for row in mine) * REPLICATES
        totals[model] = {"input_tokens_per_pass": sum(row["input_tokens"] for row in mine),
                         "max_output_tokens_per_pass": sum(row["max_output_tokens"] for row in mine),
                         "worst_case_usd_all_replicates": str(Decimal(worst) / Decimal(10**6))}
    document = {"version": VERSION, "kind": "reader-comparison-counts", "recorded_at_utc": now(),
                "captures_sha256": replay.digest((output / "captures.json").read_bytes()), "rows": rows, "totals": totals}
    replay.private_write(output / "counts.json", replay.canonical(document) + b"\n")
    print(json.dumps({"counts": len(rows), "totals": totals}))


# --------------------------------------------------------------------------- declaration

def jobs_for(manifest):
    """Dispatch order: replicate, then cohort and question as captured, then readers rotated by question."""
    jobs = []
    models = list(READERS)
    for replicate in range(REPLICATES):
        for position, row in enumerate(manifest["rows"]):
            shift = position % len(models)
            for model in models[shift:] + models[:shift]:
                jobs.append({"model": model, "cohort": row["cohort"], "question_id": row["question_id"],
                             "replicate": replicate})
    return jobs


def declare(args):
    output = args.output.absolute()
    manifest = load_captures(output)
    counts_document = json.loads((output / "counts.json").read_text())
    worst = sum(Decimal(value["worst_case_usd_all_replicates"]) for value in counts_document["totals"].values())
    require(worst <= SPENDING_CAP_USD, "worst_case_exceeds_cap")
    require(not (output / "declaration.json").exists(), "declaration_exists")
    require(not replay.git("status", "--porcelain", "--", "scripts", "Tests/Evaluation"), "sources_not_committed")
    jobs = jobs_for(manifest)
    declaration = {
        "version": VERSION, "declared_at_utc": now(), "authorization": AUTHORIZATION,
        "purpose": "P5 upper reference: hosted readers on the exact V4 prompts of the step 3 cohorts, against the local "
                   "Qwen V4 answers on the same inputs; correctness (default judge), faithful declines, presentation "
                   "defects, repeatability across replicates, latency and cost",
        "captures_sha256": replay.digest((output / "captures.json").read_bytes()),
        "counts_sha256": replay.digest((output / "counts.json").read_bytes()),
        "reference": manifest["reference"],
        "readers": {model: {**{key: value for key, value in reader.items() if key not in ("input_usd", "output_usd",
                                                                                         "price_source")},
                            "configuration": (va.configuration(model=model) if reader["route"] == "anthropic"
                                              else vg.configuration(model, reader["thinking_level"])),
                            "pricing": {**pricing(model).declaration(), "source": reader["price_source"]}}
                    for model, reader in READERS.items()},
        "request": "only the captured body's messages: the System message as the system instruction (Claude system, "
                   "Gemini systemInstruction) and the remaining turns in order; no sampling parameter, seed or Qwen "
                   "template field is sent",
        "output_limit": "the step 3 run's maximum_output per input (512 for runner document 5, 1,024 otherwise); "
                        "Gemini adds a 2,048-token thinking allowance because its thought tokens count against "
                        "maxOutputTokens",
        "thinking": "Sonnet between_tools (off), Haiku disabled (off), Gemini thinkingLevel low (its lowest; thinking "
                    "cannot be turned off). Qwen ran with thinking off.",
        "replicates": REPLICATES, "jobs": jobs, "generation_limit": len(jobs),
        "workers": WORKERS, "retry_rule": f"codes {list(RETRYABLE)} are retried at most {len(RETRY_DELAYS)} times "
                                          f"after {list(RETRY_DELAYS)} seconds; any other failure is final and "
                                          "recorded; a response cut at its output limit keeps its text as "
                                          "incomplete_result",
        "spending_cap_usd": str(SPENDING_CAP_USD), "worst_case_usd": str(worst),
        "cap_rule": "before each dispatch, spent plus that request's worst case (counted input, full output limit) "
                    "must not exceed the cap; spend uses billed usage at the declared prices",
        "measures": {
            "lexical": "as in the step 3 replay (framing_v4_variants_replay.measurement): decline measure with the "
                       "anchored source-decline extension, decline class against the declared gold delivery, AI or "
                       "memory disclaimers, copied header, raw event IDs, labels and unresolved labels, gold-turn "
                       "citation, has-reference string, self-contradiction detector v1",
            "judged": "the default judge (Vertex Sonnet 5.5, declaration version 3, prompt set v3, verdict task, "
                      "three replicates, majority vote, ties unknown) on every answer, blinded and interleaved with "
                      "the Qwen V4 answers of the step 3 replay and the V5 test",
            "repeatability": "per reader and question over the three replicates: byte-identical answers, unanimous "
                             "lexical decline status, unanimous judged verdict; Qwen over its two runs",
            "latency_cost": "wall time per request (concurrent workers), billed tokens and cost at the declared prices",
            "exclusion": "54026fce is reported separately and excluded from counts, as in the step 3 replay",
            "caveat": "Sonnet judges Sonnet- and Haiku-authored answers here; the calibration set has no Claude-authored "
                      "answer, so self-preference is not measured and is reported as a caveat",
        },
        "decision": "none pre-declared: this is a measurement for the user's choice of reader; no default changes, and "
                    "a hosted default reader would need the plan's egress and disclosure contracts first",
        "remote_calls": "Vertex AI only (llm-train-482420, global): count endpoints (free) and generation for the three "
                        "readers; the inputs are LongMemEval benchmark histories, not private user history",
        "drivers": {name: replay.digest((ROOT / "scripts" / name).read_bytes())
                    for name in ("reader_comparison.py", "vertex_anthropic.py", "vertex_gemini.py")},
        "build_commit": replay.git("rev-parse", "HEAD"),
    }
    replay.private_write(output / "declaration.json", replay.canonical(declaration) + b"\n")
    replay.private_write(output / "ledger.jsonl", b"")
    print(json.dumps({"jobs": len(jobs), "worst_case_usd": str(worst), "cap_usd": str(SPENDING_CAP_USD),
                      "declaration_sha256": replay.digest((output / "declaration.json").read_bytes())}))


# --------------------------------------------------------------------------- run

def run(args):
    output = args.output.absolute()
    declaration = json.loads((output / "declaration.json").read_text())
    require(declaration.get("version") == VERSION, "declaration_version")
    manifest = load_captures(output)
    require(replay.digest((output / "captures.json").read_bytes()) == declaration["captures_sha256"], "captures_changed")
    counts_document = json.loads((output / "counts.json").read_text())
    require(replay.digest((output / "counts.json").read_bytes()) == declaration["counts_sha256"], "counts_changed")
    for name, value in declaration["drivers"].items():
        require(replay.digest((ROOT / "scripts" / name).read_bytes()) == value, "driver_changed")
    counted = {(row["model"], row["cohort"], row["question_id"]): row for row in counts_document["rows"]}
    rows = {(row["cohort"], row["question_id"]): row for row in manifest["rows"]}
    answers = output / "answers"
    replay.private_directory(answers)
    for model in READERS:
        replay.private_directory(answers / model)
    cap = Decimal(declaration["spending_cap_usd"]) * 10**6
    lock = threading.Lock()
    done = {}
    spent = 0
    for line in (output / "ledger.jsonl").read_text().splitlines():
        record = json.loads(line)
        if record["state"] == "finished":
            done[record["job"]] = record
            spent += record.get("microusd") or 0
    token = va.AccessTokens()
    state = {"spent": spent, "stopped": None}

    def append(record):
        with open(output / "ledger.jsonl", "a") as handle:
            handle.write(json.dumps(record, sort_keys=True) + "\n")

    def work(index):
        job = declaration["jobs"][index]
        model, row = job["model"], rows[(job["cohort"], job["question_id"])]
        price = pricing(model)
        worst = price.microusd(counted[(model, job["cohort"], job["question_id"])]["input_tokens"], max_output(model, row))
        with lock:
            if state["stopped"] or state["spent"] + worst > cap:
                state["stopped"] = state["stopped"] or "cap_reached"
                return
            state["spent"] += worst  # reserved; settled below
            append({"job": index, "state": "started", "at": now()})
        url, body = generation_request(model, captured_body(output, row), row)
        failure, raw, tries, started = None, None, 0, time.monotonic()
        while True:
            tries += 1
            started = time.monotonic()
            try:
                raw = send(model, url, body, token())
                failure = None
            except va.VertexError as error:
                failure = str(error)
            if failure in RETRYABLE and tries <= len(RETRY_DELAYS):
                time.sleep(RETRY_DELAYS[tries - 1])
                continue
            break
        seconds = time.monotonic() - started
        record = {"job": index, "state": "finished", "model": model, "cohort": job["cohort"],
                  "question_id": job["question_id"], "replicate": job["replicate"], "tries": tries,
                  "seconds": round(seconds, 3), "at": now()}
        microusd = 0
        if raw is not None:
            text, usage, stop, failure = parse(model, raw)
            replay.private_write(answers / (answer_name(model, job["cohort"], job["question_id"], job["replicate"])
                                            + ".response.json"), raw)
            if usage is not None:
                microusd = price.microusd(usage["input_tokens"], usage["output_tokens"])
                record.update(input_tokens=usage["input_tokens"], output_tokens=usage["output_tokens"],
                              reasoning_tokens=usage["reasoning_tokens"],
                              visible_output_upper_bound=usage["nonreasoning_output_upper_bound"])
            if text is not None:
                path = answers / (answer_name(model, job["cohort"], job["question_id"], job["replicate"]) + ".txt")
                replay.private_write(path, text.encode())
                record["answer_sha256"] = replay.digest(text.encode())
            record["stop_reason"] = stop
        record.update(failure=failure, microusd=microusd)
        with lock:
            state["spent"] += microusd - worst
            append(record)
            if failure not in (None, "incomplete_result") and failure.startswith("http_status_4") \
                    and failure != "http_status_429":
                state["stopped"] = "client_error_" + failure
        print(json.dumps({key: record.get(key) for key in ("job", "model", "cohort", "question_id", "replicate",
                                                          "failure", "seconds", "microusd")}), flush=True)

    pending = [index for index in range(len(declaration["jobs"])) if index not in done]
    with ThreadPoolExecutor(max_workers=declaration["workers"]) as pool:
        list(pool.map(work, pending))
    finished = [json.loads(line) for line in (output / "ledger.jsonl").read_text().splitlines()]
    finished = [record for record in finished if record["state"] == "finished"]
    print(json.dumps({"finished": len(finished), "jobs": len(declaration["jobs"]), "stopped": state["stopped"],
                      "spent_usd": str(Decimal(sum(record.get("microusd") or 0 for record in finished)) / 10**6),
                      "failures": sum(1 for record in finished if record.get("failure") not in (None,
                                                                                               "incomplete_result")),
                      "incomplete": sum(1 for record in finished if record.get("failure") == "incomplete_result")}))


# --------------------------------------------------------------------------- measurement

def latest_records(output: Path):
    out = {}
    for line in (output / "ledger.jsonl").read_text().splitlines():
        record = json.loads(line)
        if record["state"] == "finished":
            out[record["job"]] = record
    return out


def answered_rows(output: Path, dataset: Path, qwen_runs):
    """Every answer to measure: (reader, replicate label, cohort, question ID, answer or None, label map, record).
    Qwen answers come from the V4 arm of each reference run directory in `qwen_runs`."""
    declaration = json.loads((output / "declaration.json").read_text())
    manifest = load_captures(output)
    rows = {(row["cohort"], row["question_id"]): row for row in manifest["rows"]}
    records = latest_records(output)
    out = []
    for index, job in enumerate(declaration["jobs"]):
        record = records.get(index)
        path = output / "answers" / (answer_name(job["model"], job["cohort"], job["question_id"], job["replicate"]) + ".txt")
        answer = path.read_text() if record and path.exists() else None
        row = rows[(job["cohort"], job["question_id"])]
        out.append({"reader": job["model"], "replicate": f"r{job['replicate']}", "cohort": job["cohort"],
                    "question_id": job["question_id"], "answer": answer, "label_map": row["citation_labels"],
                    "record": record or {}, "status": "measured" if answer is not None else "not_answered"})
    for run_dir in qwen_runs:
        run_dir = run_dir.absolute()
        reference = json.loads((run_dir / "declaration.json").read_text())
        ledger_rows = replay.ledger(run_dir)
        for index, entry in enumerate(reference["runs"]):
            if entry["arm"] != "v4-default" or (entry["cohort"], entry["question_id"]) not in rows:
                continue
            row = rows[(entry["cohort"], entry["question_id"])]
            require(entry["runner_input_sha256"] == row["runner_input_sha256"], "qwen_input_mismatch")
            report, item, answer = native_answer(run_dir, ledger_rows, index, entry["attempt"])
            same_delivery = item is not None and replay.ranges_digest(item.get("delivered_ranges")) \
                == entry["declared_delivered_ranges_sha256"]
            usage = (item or {}).get("provider_usage") or {}
            out.append({"reader": "qwen-local", "replicate": reference["version"], "cohort": entry["cohort"],
                        "question_id": entry["question_id"], "answer": answer,
                        "label_map": (item or {}).get("citation_labels"),
                        "record": {"seconds": ((item or {}).get("provider_milliseconds") or 0) / 1000 or None,
                                   "input_tokens": usage.get("promptTokens"), "output_tokens": usage.get("completionTokens"),
                                   "failure": (item or {}).get("failure"), "delivery_as_declared": same_delivery,
                                   "framing": (item or {}).get("context_framing")},
                        "status": "measured" if answer is not None else "not_answered"})
    return declaration, manifest, out


def measure_rows(output: Path, dataset: Path, qwen_runs):
    declaration, manifest, answered = answered_rows(output, dataset, qwen_runs)
    plan = v4v.cohorts()
    frozen = v4v.frozen_inputs(dataset, plan)
    sources = {(qid, cohort): run for cohort in COHORT_ORDER for qid, run, _, _ in plan[cohort][0]}
    rows = {(row["cohort"], row["question_id"]): row for row in manifest["rows"]}
    measured = []
    for entry in answered:
        captured = rows[(entry["cohort"], entry["question_id"])]
        history, document, _ = frozen[(entry["question_id"], sources[(entry["question_id"], entry["cohort"])])]
        probe = history["episodes"][0]
        out = {key: entry[key] for key in ("reader", "replicate", "cohort", "question_id", "status")}
        out.update(question_type=captured["question_type"], abstention=captured["abstention"],
                   declared_gold_delivery=captured["declared_gold_delivery"], record=entry["record"])
        answer = entry["answer"]
        if answer is not None:
            known = [event["id"] for event in document["events"]]
            values = replay.measure_answer(answer, probe["prompt"], probe["answer"], known, entry["label_map"])
            base_outcome = values.pop("outcome")
            values.pop("decline_opening", None)
            out.update(base_outcome=base_outcome, answer_sha256=replay.digest(answer.encode()), **values,
                       **v5plan.decline_outcome(answer), **v5plan.cites_gold(answer, history, entry["label_map"]),
                       **v4v.self_contradiction(answer, probe["answer"], bool(probe["abstention"])))
            out["decline_class"] = replay.decline_class(out["outcome"], out["abstention"], out["declared_gold_delivery"])
        measured.append(out)
    return declaration, measured, answered, frozen, sources


SUBSETS = {
    "answerable_gold_whole": lambda row: not row["abstention"] and row["declared_gold_delivery"] == "whole",
    "answerable_gold_partial": lambda row: not row["abstention"] and row["declared_gold_delivery"] == "partial",
    "answerable_gold_none": lambda row: not row["abstention"] and row["declared_gold_delivery"] == "none",
    "abstention": lambda row: row["abstention"],
}


def lexical_counts(chosen):
    done = [row for row in chosen if row["status"] == "measured"]
    return {"answers": len(done), "missing": len(chosen) - len(done),
            "declines": sum(1 for row in done if v5plan.is_decline(row["outcome"])),
            "false_declines": sum(1 for row in done if row["decline_class"] == "false_decline"),
            "ai_disclaimer": sum(1 for row in done if row["ai_disclaimer"]),
            "copied_header": sum(row["copied_header"] for row in done),
            "with_raw_event_ids": sum(1 for row in done if row["raw_event_ids"]),
            "self_contradiction": sum(1 for row in done if row["self_contradiction"]),
            "cited_labels": sum(row["cited_labels"] for row in done),
            "unresolved_labels": sum(row["unresolved_labels"] for row in done),
            "cites_gold_turn": sum(1 for row in done if row["cites_gold_turn"]),
            "contains_reference": sum(1 for row in done if row["contains_reference"]),
            "latex": sum(1 for row in done if row["latex"]),
            "median_words": statistics.median([row["answer_words"] for row in done]) if done else None}


def readers_of(rows):
    return [reader for reader in ["qwen-local", *READERS] if any(row["reader"] == reader for row in rows)]


def lexical_tables(rows):
    tables = {}
    for reader in readers_of(rows):
        mine = [row for row in rows if row["reader"] == reader and row["question_id"] not in EXCLUDED_FROM_COUNTS]
        tables[reader] = {}
        for cohort in COHORT_ORDER:
            subset = [row for row in mine if row["cohort"] == cohort]
            tables[reader][cohort] = {"all": lexical_counts(subset),
                                      **{name: lexical_counts([row for row in subset if test(row)])
                                         for name, test in SUBSETS.items()}}
    return tables


def repeatability(rows, key):
    """Per reader: questions with all samples present, and how many agree on `key` across samples."""
    out = {}
    for reader in readers_of(rows):
        groups = {}
        for row in rows:
            if row["reader"] == reader and row["question_id"] not in EXCLUDED_FROM_COUNTS:
                groups.setdefault((row["cohort"], row["question_id"]), []).append(row)
        complete = [group for group in groups.values() if all(row["status"] == "measured" for row in group)
                    and len(group) >= 2]
        out[reader] = {"questions": len(complete), "samples_per_question": sorted({len(group) for group in complete}),
                       "unanimous": sum(1 for group in complete if len({key(row) for row in group}) == 1)}
    return out


def operations(rows):
    out = {}
    for reader in readers_of(rows):
        mine = [row["record"] for row in rows if row["reader"] == reader]
        seconds = sorted(record["seconds"] for record in mine if record.get("seconds"))
        out[reader] = {"requests": len(mine),
                       "failures": sum(1 for record in mine if record.get("failure") not in (None, "incomplete_result")),
                       "incomplete": sum(1 for record in mine if record.get("failure") == "incomplete_result"),
                       "retried": sum(1 for record in mine if (record.get("tries") or 1) > 1),
                       "median_seconds": round(statistics.median(seconds), 2) if seconds else None,
                       "p90_seconds": round(seconds[int(0.9 * (len(seconds) - 1))], 2) if seconds else None,
                       "input_tokens": sum(record.get("input_tokens") or 0 for record in mine),
                       "output_tokens": sum(record.get("output_tokens") or 0 for record in mine),
                       "reasoning_tokens": sum(record.get("reasoning_tokens") or 0 for record in mine),
                       "usd": str(Decimal(sum(record.get("microusd") or 0 for record in mine)) / 10**6)}
    return out


def measure(args):
    output = args.output.absolute()
    _declaration, rows, _answered, _frozen, _sources = measure_rows(output, args.dataset, args.qwen_run)
    document = {"version": VERSION, "kind": "reader-comparison-measure", "recorded_at_utc": now(),
                "lexical": lexical_tables(rows),
                "repeatability": {"byte_identical": repeatability(rows, lambda row: row["answer_sha256"]),
                                  "decline_status": repeatability(rows, lambda row: v5plan.is_decline(row["outcome"]))},
                "operations": operations(rows),
                "excluded": {reader: [{key: row.get(key) for key in ("cohort", "replicate", "outcome", "decline_class")}
                                      for row in rows if row["reader"] == reader and row["question_id"] in EXCLUDED_FROM_COUNTS]
                             for reader in readers_of(rows)},
                "rows": [{key: value for key, value in row.items() if key != "record"} for row in rows]}
    replay.private_write(output / "measure.json", replay.canonical(document) + b"\n")
    print(json.dumps({key: document[key] for key in ("repeatability", "operations")}, indent=1))


# --------------------------------------------------------------------------- judging

def judge_set(args):
    """Blinded verdict items for every hosted and Qwen answer, interleaved by a seeded order. No judge call."""
    import judge_calibration as jc
    output = args.output.absolute()
    declaration, rows, answered, frozen, sources = measure_rows(output, args.dataset, args.qwen_run)
    seed = replay.digest((output / "declaration.json").read_bytes())
    records = jc.load_dataset(args.dataset)
    candidates = []
    for index, (entry, row) in enumerate(zip(answered, rows)):
        if entry["answer"] is None:
            continue
        history, _document, _ = frozen[(entry["question_id"], sources[(entry["question_id"], entry["cohort"])])]
        arm = f"{entry['reader']}:{entry['replicate']}"
        candidate = jc.new_candidate(run=f"reader-comparison-{entry['cohort']}", run_family="reader-comparison",
                                     arm=arm, question_id=entry["question_id"],
                                     answer_model=QWEN if entry["reader"] == "qwen-local" else entry["reader"],
                                     operational_complete=True, answer_sha256=replay.digest(entry["answer"].encode()))
        jc.attach_question(candidate, records)
        require(candidate["reference"] is not None, "question_missing_from_dataset")
        candidate["scrub_ids"].update(event["id"] for event in history["events"])
        jc.verify_answer(candidate, entry["answer"])
        candidates.append((jc.rank(seed, str(index), entry["question_id"], arm), index, entry, candidate))
    candidates.sort(key=lambda value: value[0])
    items, keys = [], []
    for position, (_rank, index, entry, candidate) in enumerate(candidates, start=1):
        item, replaced = jc.blind_item(candidate, f"item-{position:04d}")
        items.append(item)
        keys.append({"item_id": item["item_id"], "row_index": index, "reader": entry["reader"],
                     "replicate": entry["replicate"], "cohort": entry["cohort"], "question_id": entry["question_id"],
                     "abstention": bool(candidate["abstention"]), "question_type": candidate["question_type"],
                     "answer_sha256": candidate["answer_sha256"], "item_sha256": replay.digest(replay.canonical(item)),
                     "identifier_substitutions": replaced})
    set_id = "jrc-" + replay.digest(replay.canonical({"seed": seed, "keys": [[key["row_index"], key["answer_sha256"]]
                                                                             for key in keys]}))[:16]
    items_document = {"format": jc.ITEMS_FORMAT, "set_id": set_id, "items": items}
    key_document = {"format": replay.JUDGE_KEY_FORMAT, "set_id": set_id, "seed": seed, "items": keys}
    require(not jc.blinding_violations(items_document, key_document), "blinding_violation")
    manifest = replay.write_judge_set(output / "judge-set", items_document, key_document, "reader-comparison", seed)
    print(json.dumps({"set_id": manifest["set_id"], "items": manifest["item_count"],
                      "items_sha256": manifest["items_sha256"], "readers": {reader: sum(1 for key in keys
                                                                                        if key["reader"] == reader)
                                                                            for reader in readers_of(rows)},
                      "identity_mention_items": len(manifest["identity_mention_items"])}))


def score(args):
    """Joins the default judge's labels with the measured rows. Counts, IDs and classes only."""
    import judge_calibration as jc
    output = args.output.absolute()
    _declaration, rows, _answered, _frozen, _sources = measure_rows(output, args.dataset, args.qwen_run)
    key_document = jc.load_json(output / "judge-set" / "key.json")
    labels_document = jc.load_json(args.labels)
    require(labels_document.get("set_id") == key_document["set_id"], "labels_set_mismatch")
    require(labels_document.get("replicates") == 3 and labels_document.get("complete") is True, "labels_incomplete")
    for key in key_document["items"]:
        row = rows[key["row_index"]]
        require(row["question_id"] == key["question_id"] and row["reader"] == key["reader"], "key_row_mismatch")
        verdicts = [entry.get("verdict") for entry in labels_document["labels"].get(key["item_id"], [{}, {}, {}])]
        row["replicate_verdicts"] = verdicts
        row["verdict"] = replay.majority_of_three(verdicts)

    def verdicts(chosen):
        done = [row for row in chosen if row.get("verdict")]
        return {"answers": len(done), **{label: sum(1 for row in done if row["verdict"] == label)
                                         for label in ("accept", "reject", "unknown")}}
    tables = {}
    counted = [row for row in rows if row["question_id"] not in EXCLUDED_FROM_COUNTS]
    for reader in readers_of(rows):
        mine = [row for row in counted if row["reader"] == reader]
        retrieval = [row for row in mine if row["cohort"] != "recent-only-21"]
        tables[reader] = {
            "all": verdicts(mine),
            **{cohort: verdicts([row for row in mine if row["cohort"] == cohort]) for cohort in COHORT_ORDER},
            "retrieval_answerable_gold_whole": verdicts([row for row in retrieval if SUBSETS["answerable_gold_whole"](row)]),
            "retrieval_answerable_gold_partial": verdicts([row for row in retrieval
                                                           if SUBSETS["answerable_gold_partial"](row)]),
            "retrieval_answerable_gold_none": verdicts([row for row in retrieval if SUBSETS["answerable_gold_none"](row)]),
            "abstention": verdicts([row for row in mine if row["abstention"]]),
            "preference": verdicts([row for row in retrieval if row["question_type"] == v4v.PREFERENCE_TYPE]),
            "temporal": verdicts([row for row in retrieval if row["question_type"] == v4v.TEMPORAL_TYPE
                                  and not row["abstention"]]),
        }
    document = {"version": VERSION, "kind": "reader-comparison-score", "recorded_at_utc": now(),
                "set_id": key_document["set_id"], "judge": labels_document.get("judge"),
                "labels_declaration_sha256": labels_document.get("declaration_sha256"),
                "prompts": labels_document.get("prompts"), "tables": tables,
                "verdict_repeatability": repeatability([row for row in rows if row.get("verdict")],
                                                       lambda row: row["verdict"]),
                "per_question": {reader: {case_name(row["cohort"], row["question_id"]): [] for row in rows
                                          if row["reader"] == reader} for reader in readers_of(rows)}}
    for row in rows:
        if row.get("verdict"):
            document["per_question"][row["reader"]][case_name(row["cohort"], row["question_id"])].append(
                [row["replicate"], row["verdict"], row.get("outcome")])
    replay.private_write(output / "score.json", replay.canonical(document) + b"\n")
    print(json.dumps({key: document[key] for key in ("set_id", "tables", "verdict_repeatability")}, indent=1))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    commands = parser.add_subparsers(dest="command", required=True)
    for name in ("capture", "count", "declare", "run", "measure", "judge-set", "score"):
        command = commands.add_parser(name)
        command.add_argument("--output", type=Path, required=True)
        if name in ("capture", "measure", "judge-set", "score"):
            command.add_argument("--dataset", type=Path, required=True)
        if name == "capture":
            import retrieval_harness as harness
            command.add_argument("--reference", type=Path, required=True, help="the step 3 replay output directory")
            command.add_argument("--tokenizer", type=Path, default=harness.DEFAULT_TOKENIZER)
        if name in ("measure", "judge-set", "score"):
            command.add_argument("--qwen-run", type=Path, action="append", default=[],
                                 help="a local replay output directory whose v4-default arm is the Qwen baseline")
        if name == "score":
            command.add_argument("--labels", type=Path, required=True)
    args = parser.parse_args(argv)
    import judge_calibration as jc
    import retrieval_harness as harness
    try:
        {"capture": capture, "count": count, "declare": declare, "run": run, "measure": measure,
         "judge-set": judge_set, "score": score}[args.command](args)
    except (ComparisonError, va.VertexError, replay.ReplayError, v5plan.PlanError, v4v.PlanError,
            jc.CalibrationError, harness.HarnessError) as error:
        print(json.dumps({"error": str(error)}))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
